#!/usr/bin/env python3
"""导出数据库数据为 SQL 脚本"""
import sys
from sqlalchemy import create_engine, text
from config.settings import settings

def export_database():
    """导出数据库数据"""
    engine = create_engine(settings.database_url)
    
    with engine.connect() as conn:
        # 获取所有表
        result = conn.execute(text("""
            SELECT tablename FROM pg_tables 
            WHERE schemaname = 'public'
            ORDER BY tablename
        """))
        tables = [row[0] for row in result]
        
        print("-- Dual Agent Chat Database Export")
        print("-- Generated by export_database.py")
        print()
        
        for table in tables:
            print(f"-- Table: {table}")
            
            # 获取表数据
            result = conn.execute(text(f"SELECT * FROM {table}"))
            rows = result.fetchall()
            columns = result.keys()
            
            if rows:
                print(f"-- Exporting {len(rows)} rows from {table}")
                for row in rows:
                    values = []
                    for val in row:
                        if val is None:
                            values.append('NULL')
                        elif isinstance(val, str):
                            # 转义单引号
                            escaped = val.replace("'", "''")
                            values.append(f"'{escaped}'")
                        elif isinstance(val, bool):
                            values.append('TRUE' if val else 'FALSE')
                        else:
                            values.append(str(val))
                    
                    cols = ', '.join(columns)
                    vals = ', '.join(values)
                    print(f"INSERT INTO {table} ({cols}) VALUES ({vals});")
                print()
            else:
                print(f"-- No data in {table}")
                print()

if __name__ == '__main__':
    try:
        export_database()
    except Exception as e:
        print(f"Error: {e}", file=sys.stderr)
        sys.exit(1)
