"""Add message_relevance_scores table

Revision ID: 3637cd9e8cd9
Revises: c7533f416258
Create Date: 2026-02-24 13:15:26.757655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3637cd9e8cd9'
down_revision: Union[str, None] = 'c7533f416258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_relevance_scores',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('evaluation_comment', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('relevance_score >= 0 AND relevance_score <= 100', name='check_relevance_score_range'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id')
    )
    op.drop_index('idx_audit_logs_agent_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_operation_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_topic_time', table_name='audit_logs')
    op.drop_index('idx_messages_topic_time', table_name='messages')
    op.drop_index('idx_summary_history_topic_time', table_name='summary_history')
    op.drop_index('idx_summary_jobs_status_time', table_name='summary_jobs')
    op.drop_index('idx_summary_jobs_topic', table_name='summary_jobs')
    op.add_column('topics', sa.Column('topic_description', sa.Text(), nullable=True))
    op.drop_index('idx_topics_closing_timeout', table_name='topics')
    op.drop_index('idx_topics_created_at', table_name='topics')
    op.drop_index('idx_topics_status', table_name='topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_topics_status', 'topics', ['status'], unique=False)
    op.create_index('idx_topics_created_at', 'topics', ['created_at'], unique=False)
    op.create_index('idx_topics_closing_timeout', 'topics', ['status', 'closing_requested_at'], unique=False)
    op.drop_column('topics', 'topic_description')
    op.create_index('idx_summary_jobs_topic', 'summary_jobs', ['topic_id'], unique=False)
    op.create_index('idx_summary_jobs_status_time', 'summary_jobs', ['status', 'created_at'], unique=False)
    op.create_index('idx_summary_history_topic_time', 'summary_history', ['topic_id', 'created_at'], unique=False)
    op.create_index('idx_messages_topic_time', 'messages', ['topic_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_topic_time', 'audit_logs', ['topic_id', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_operation_time', 'audit_logs', ['operation_type', 'created_at'], unique=False)
    op.create_index('idx_audit_logs_agent_time', 'audit_logs', ['agent_id', 'created_at'], unique=False)
    op.drop_table('message_relevance_scores')
    # ### end Alembic commands ###
