"""Initial migration: create all tables

Revision ID: c7533f416258
Revises: 
Create Date: 2026-02-13 21:36:04.440077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7533f416258'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('auth_token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=True),
    sa.Column('agent_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topics',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('llm_suggestion', sa.String(length=20), nullable=True),
    sa.Column('end_score', sa.Float(), nullable=True),
    sa.Column('token_count_since_summary', sa.Integer(), nullable=False),
    sa.Column('summary_threshold', sa.Integer(), nullable=True),
    sa.Column('last_summarized_message_id', sa.String(length=36), nullable=True),
    sa.Column('pending_summary_job', sa.Boolean(), nullable=False),
    sa.Column('agent_a_wants_close', sa.Boolean(), nullable=False),
    sa.Column('agent_b_wants_close', sa.Boolean(), nullable=False),
    sa.Column('closing_requested_by', sa.String(length=36), nullable=True),
    sa.Column('closing_requested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("llm_suggestion IS NULL OR llm_suggestion IN ('continue', 'change_angle', 'suggest_end', 'force_end')", name='check_llm_suggestion'),
    sa.CheckConstraint("status IN ('active', 'closing_pending', 'closed')", name='check_topic_status'),
    sa.CheckConstraint('end_score IS NULL OR (end_score >= 0 AND end_score <= 100)', name='check_end_score_range'),
    sa.CheckConstraint('token_count_since_summary >= 0', name='check_token_count_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('actual_tokens', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("content != ''", name='check_content_not_empty'),
    sa.CheckConstraint('actual_tokens >= 0', name='check_actual_tokens_positive'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('llm_suggestion', sa.String(length=20), nullable=False),
    sa.Column('end_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("llm_suggestion IN ('continue', 'change_angle', 'suggest_end', 'force_end')", name='check_history_llm_suggestion'),
    sa.CheckConstraint('end_score >= 0 AND end_score <= 100', name='check_history_end_score_range'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('summary_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic_id', sa.String(length=36), nullable=False),
    sa.Column('start_message_id', sa.String(length=36), nullable=True),
    sa.Column('end_message_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'processing', 'done', 'failed')", name='check_summary_job_status'),
    sa.CheckConstraint('retry_count >= 0', name='check_retry_count_positive'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes for performance optimization
    # Topics indexes
    op.create_index('idx_topics_status', 'topics', ['status'])
    op.create_index('idx_topics_created_at', 'topics', ['created_at'])
    op.create_index('idx_topics_closing_timeout', 'topics', ['status', 'closing_requested_at'])
    
    # Messages indexes
    op.create_index('idx_messages_topic_time', 'messages', ['topic_id', 'created_at'])
    
    # Summary Jobs indexes
    op.create_index('idx_summary_jobs_topic', 'summary_jobs', ['topic_id'])
    op.create_index('idx_summary_jobs_status_time', 'summary_jobs', ['status', 'created_at'])
    
    # Summary History indexes
    op.create_index('idx_summary_history_topic_time', 'summary_history', ['topic_id', 'created_at'])
    
    # Audit Logs indexes
    op.create_index('idx_audit_logs_topic_time', 'audit_logs', ['topic_id', 'created_at'])
    op.create_index('idx_audit_logs_agent_time', 'audit_logs', ['agent_id', 'created_at'])
    op.create_index('idx_audit_logs_operation_time', 'audit_logs', ['operation_type', 'created_at'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.drop_index('idx_audit_logs_operation_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_agent_time', table_name='audit_logs')
    op.drop_index('idx_audit_logs_topic_time', table_name='audit_logs')
    op.drop_index('idx_summary_history_topic_time', table_name='summary_history')
    op.drop_index('idx_summary_jobs_status_time', table_name='summary_jobs')
    op.drop_index('idx_summary_jobs_topic', table_name='summary_jobs')
    op.drop_index('idx_messages_topic_time', table_name='messages')
    op.drop_index('idx_topics_closing_timeout', table_name='topics')
    op.drop_index('idx_topics_created_at', table_name='topics')
    op.drop_index('idx_topics_status', table_name='topics')
    
    # Drop tables
    op.drop_table('summary_jobs')
    op.drop_table('summary_history')
    op.drop_table('messages')
    op.drop_table('topics')
    op.drop_table('audit_logs')
    op.drop_table('agents')
    # ### end Alembic commands ###
